### PR TITLE
PR to update SethDart

### PR DESCRIPTION
**Pull request by rgleason**
Utilizes Appveyor, Travis, CircleCI and Cloudsmith services to build for mulitple environments. Based on Frontend1 by Leamas and bdbcat.
This updates this important plugin to work with the new Plugin Manager system

### CODE REVIEW

**Comment by rgleason** [comment]
When do you plan on merging this?  I am not going to rebase it!

**Comment by SethDart** [comment]
Hi Rick,

I'm not going to merge this as is: it's full of un-needed code for this very simple plugin.
README is related to squidio plugin, same for other files. There's no need for GL/GLES, bzip2, jsoncpp, wxcurl, zlib...

This needs huge work before it can be merged.

Thanks,
Jean-Eudes

**Comment by rgleason** [comment]
I don't agree, but will withdraw it.  I am surprised that you have this attitude when you asked that I implement Dave's Frontend1 and I have done so.  Frontend1 is used for many plugins and is an effective tool for multiple builds.

I will continue to build vdr for awhile, but you will have to find another solution that solves the problems that you see.

**Comment by rgleason** [comment]
By the way, 
This code is taken directly from Dave Register's Oesenc_pi  Frontend1 and it  has been simplified, so I don't really think you are reasonable.

**Comment by rgleason** [comment]
I had understood that we had agreed, that I would hand this off to you once working. I have other things that need to be done and will not be supporting this plugin past integration of the android builds, such that it works properly.

**Comment by SethDart** [comment]
Really, I've no problem with the purpose of this patch ;-)

But, as I said, this patch include a lot of code that's not required for this plugin (GL/GLES, bzip2, jsoncpp, wxcurl, zlib)

To me, it doesn't make sense to add all these files to VDR. They're probably required for squidio or oesenc or others plugins but they're not required for the vdr.

VDR is a very simple plugin: listen to nmea stream and record it to a (text) file. Nothing more than that.

**Comment by rgleason** [comment]
Well you are welcome to cut it down, but I am going to stop once we have the android builds and all other plugins working. Perfection can be done later.  It may be a simple plugin (that I use all the time) but the frontend builds for about 10-13 environments and that is not simple!

**Comment by rgleason** [comment]
I believe  wxJSON, wxcurl, bzip and maybe zlib are required for the frontend to make tarballs for various builds.

**Pull request closed without merging**
